### ISSUE TITLE
[BUG] - http 404 from cardano-api doc site

### ISSUE THREAD

**Issue by kayvank** [IntersectMBO/cardano-api#546] opened 2024-05-29 08:34 UTC
*Internal*   if an IOHK staff member.

**Area**
*http 404*    haddocks.

**Summary**
getting http 404 from cardano-api documentation site

**Steps to reproduce**
1. Go to:  https://cardano-api.cardano.intersectmbo.org/cardano-api/Cardano-Api-SerialiseJSON.html#v:writeFileJSON
2. See error

**Expected behavior**
return http code of 200 and serve the document
**System info (please complete the following information):**
- OS Name:nixos. browser=brave. Also tried this with `curl`
- OS Version [e.g. 20.04]

**Comment by smelc** [comment] 2024-05-29 12:41
@carbolymer> the root page is up: https://cardano-api.cardano.intersectmbo.org/

So I guess we're not exporting/building some (nested) Haddocks?

**Comment by smelc** [comment] 2024-05-31 07:35
Probably a duplicate of: https://github.com/IntersectMBO/cardano-api/issues/546

**Comment by carbolymer** [comment] 2024-07-03 11:35
from @kayvank on Slack:

> for the links that don't work:
> https://cardano-api.cardano.intersectmbo.org/cardano-api/Cardano-Api.html
> if you change them to:
> https://cardano-api.cardano.intersectmbo.org/cardano-api-8.49.0.0-inplace/Cardano-Api.html
> then they work.
> In otherworkds, change ..../cardano-api/ .....    to ...../cardano-api-8.49.0.0-inplace/....

**Closed** 2024-07-04 10:54 UTC
